highlight-font: '"GT Walsheim", "gt_walsheim_regular", "Avant Garde Gothic ITCW01Dm", "Avant Garde", "Helvetica Neue", "Arial" '
body: '"Helvetica Neue", "Arial", san-serif'
code: '"Monaco", "Menlo", "Consolas", "Courier New", monospace'

highlight-color: "#A1A1A1"
highlight-dark-color: "#737373"
darker-color: "#4D4D4D"
darker-dark-color: "#000000"
background-color: "#E3E3E3"
alt-link-color: "#0008FF"
warning-color: "#FF8800"
